"""Learning-based prediction and refinement namespace."""

from .base import BasePredictor, BaseRefiner, PredictionResult
from .bisection import BisectionConfig, BisectionResult, bisect_segment
from .eval import summarize_prediction_route
from .predictors import ConstantDecisionPredictor, ConstantPredictor, NeuralDecisionPredictor
from .refiners import (
    DiffProjectionRefiner,
    ExactSolverProjectionRefiner,
    HomeomorphicProjectionRefiner,
    IPNNBisectionRefiner,
    IdentityRefiner,
    InitializedOptSolverRefiner,
    ProjectionRefiner,
    RayBisectionRefiner,
)
from .training import (
    build_learning_mapping_payload,
    build_inn_runtime_args,
    build_predictor_training_payload,
    build_training_payload,
    load_or_train_decision_predictor,
    load_or_train_learning_mapping,
    load_or_train_inn_mapping,
    load_or_train_ipnn_mapping,
    load_or_train_mapping,
    normalize_mapping_type,
    prepare_learning_mapping,
    prepare_decision_predictor,
    save_training_record,
    train_decision_predictor,
    train_ipnn_mapping,
    train_mdh_mapping,
    training_time_from_record,
    unsupervised_training_mdh,
)

__all__ = [
    "BasePredictor",
    "BaseRefiner",
    "BisectionConfig",
    "BisectionResult",
    "ConstantDecisionPredictor",
    "ConstantPredictor",
    "DiffProjectionRefiner",
    "ExactSolverProjectionRefiner",
    "HomeomorphicProjectionRefiner",
    "IPNNBisectionRefiner",
    "InitializedOptSolverRefiner",
    "IdentityRefiner",
    "NeuralDecisionPredictor",
    "PredictionResult",
    "ProjectionRefiner",
    "RayBisectionRefiner",
    "bisect_segment",
    "build_learning_mapping_payload",
    "build_inn_runtime_args",
    "build_predictor_training_payload",
    "build_training_payload",
    "load_or_train_decision_predictor",
    "load_or_train_learning_mapping",
    "load_or_train_mapping",
    "load_or_train_inn_mapping",
    "load_or_train_ipnn_mapping",
    "normalize_mapping_type",
    "prepare_learning_mapping",
    "prepare_decision_predictor",
    "save_training_record",
    "summarize_prediction_route",
    "train_decision_predictor",
    "train_ipnn_mapping",
    "train_mdh_mapping",
    "training_time_from_record",
    "unsupervised_training_mdh",
]
